/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JPanel;
import model.directories.DoctorDirectory;
import model.directories.EncounterDirectory;
import model.directories.PatientDirectory;

/**
 *
 * @author ASUS
 */
public class CreateEncounterPanel extends javax.swing.JPanel {
    
    JPanel bottomPanel;
    DoctorDirectory allDoctors;
    EncounterDirectory allEncounters;
    PatientDirectory allPatients;

    /**
     * Creates new form CreateEncounterPanel
     */
    public CreateEncounterPanel(JPanel bottomPanel, DoctorDirectory allDoctors, EncounterDirectory allEncounters, PatientDirectory allPatients) {
        initComponents();
        this.allDoctors = allDoctors;
        this.allEncounters = allEncounters;
        this.allPatients = allPatients;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
