/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import static java.awt.image.ImageObserver.HEIGHT;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.dataModels.Doctor;
import model.dataModels.Patient;
import model.directories.EncounterDirectory;
import model.directories.PatientDirectory;

/**
 *
 * @author ASUS
 */
public class CreateEncounterPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEncounterPanel
     */
    JPanel rightPanel; 
    EncounterDirectory allEncounters; 
    PatientDirectory allPatients;
    
    public CreateEncounterPanel(JPanel rightPanel, EncounterDirectory allEncounters, PatientDirectory allPatients) {
        initComponents();
        this.rightPanel = rightPanel;
        this.allEncounters = allEncounters;
        this.allPatients = allPatients;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        patientListTable = new javax.swing.JTable();
        patientDetailsTitleLabel = new javax.swing.JLabel();
        recordEncounterButton = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        houseLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        communityLabel = new javax.swing.JLabel();
        nameAnsLabel = new javax.swing.JLabel();
        houseAnsLabel = new javax.swing.JLabel();
        ageAnsLabel = new javax.swing.JLabel();
        genderAnsLabel = new javax.swing.JLabel();
        dateAnsLabel = new javax.swing.JLabel();
        phoneNumberAnsLabel = new javax.swing.JLabel();
        communityAnsLabel = new javax.swing.JLabel();

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setText("Create an Encounter");

        patientListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Patient Age", "Community", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(patientListTable);

        patientDetailsTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        recordEncounterButton.setText("Record Encounter");
        recordEncounterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordEncounterButtonActionPerformed(evt);
            }
        });

        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionLabel.setText("Select a Patient:");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        houseLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        communityLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(recordEncounterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descriptionLabel))
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientDetailsTitleLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(communityLabel)
                                    .addComponent(houseLabel)
                                    .addComponent(ageLabel)
                                    .addComponent(genderLabel)
                                    .addComponent(dateLabel)
                                    .addComponent(phoneNumberLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameAnsLabel)
                                    .addComponent(communityAnsLabel)
                                    .addComponent(houseAnsLabel)
                                    .addComponent(ageAnsLabel)
                                    .addComponent(genderAnsLabel)
                                    .addComponent(dateAnsLabel)
                                    .addComponent(phoneNumberAnsLabel))))))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(titleLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(descriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(recordEncounterButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(patientDetailsTitleLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(houseLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ageLabel)
                                .addGap(18, 18, 18)
                                .addComponent(genderLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(phoneNumberLabel)
                                .addGap(18, 18, 18)
                                .addComponent(communityLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameAnsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(houseAnsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ageAnsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(genderAnsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dateAnsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(phoneNumberAnsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(communityAnsLabel)))))
                .addContainerGap(439, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void recordEncounterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordEncounterButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = patientListTable.getSelectedRow();
        if (selectedIndex <0){
            JOptionPane.showMessageDialog(this, "Please select an entry to view", "Error", HEIGHT);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) patientListTable.getModel();
        Patient selectedPatient = (Patient) model.getValueAt(selectedIndex, 0);
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String date = sdf.format(selectedPatient.getDateOfBirth());
        
        patientDetailsTitleLabel.setText("Selected Patient Details:");
        nameLabel.setText("Name:");
        nameAnsLabel.setText(selectedPatient.getName());
        ageLabel.setText("Age:");
        ageAnsLabel.setText(String.valueOf(selectedPatient.getAge()));
        houseLabel.setText("House:");
        houseAnsLabel.setText(selectedPatient.getHouse());
        genderLabel.setText("Gender:");
        genderAnsLabel.setText(selectedPatient.getGender());
        phoneNumberLabel.setText("Phone Number:");
        phoneNumberAnsLabel.setText(String.valueOf(selectedPatient.getPhoneNumber()));
        communityLabel.setText("Community:");
        communityAnsLabel.setText(selectedPatient.getCommunity());
        dateLabel.setText("Date:");
        dateAnsLabel.setText(date);
        
    }//GEN-LAST:event_recordEncounterButtonActionPerformed
    
    void populateTable() {
        DefaultTableModel model = (DefaultTableModel) patientListTable.getModel();
        model.setRowCount(0);
        for(Patient patient : allPatients.getAllPatients()) {
            Object[] row = new Object[4];
            row[0] = patient;
            row[1] = patient.getAge();
            row[2] = patient.getCommunity();
            row[3] = patient.getGender();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageAnsLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel communityAnsLabel;
    private javax.swing.JLabel communityLabel;
    private javax.swing.JLabel dateAnsLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel genderAnsLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel houseAnsLabel;
    private javax.swing.JLabel houseLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel nameAnsLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel patientDetailsTitleLabel;
    private javax.swing.JTable patientListTable;
    private javax.swing.JLabel phoneNumberAnsLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JButton recordEncounterButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
