/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class CreateEncounterPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEncounterPanel
     */

    String patientName;
    
    private static final String username = "root";
    private static final String password = "root";
    private static final String dataConnector = "jdbc:mysql://localhost:3306/connector";
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public CreateEncounterPanel() {
        initComponents();
        populateTable();
        
        heartbeatField.setEditable(false);
        temperatureField.setEditable(false);
        bloodPressureField.setEditable(false);
        diagnosisField.setEditable(false);        
        saveButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        patientListTable = new javax.swing.JTable();
        recordEncounterButton = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        heartbeatLabel = new javax.swing.JLabel();
        encounterDescriptionLabel = new javax.swing.JLabel();
        heartbeatField = new javax.swing.JTextField();
        temperatureLabel = new javax.swing.JLabel();
        temperatureField = new javax.swing.JTextField();
        bloodPressureLabel = new javax.swing.JLabel();
        bloodPressureField = new javax.swing.JTextField();
        diagnosisLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnosisField = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setText("Create an Encounter");

        patientListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Patient Age", "Community", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(patientListTable);

        recordEncounterButton.setText("Record Encounter");
        recordEncounterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordEncounterButtonActionPerformed(evt);
            }
        });

        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionLabel.setText("Select a Patient:");

        heartbeatLabel.setText("Heartbeat:");

        encounterDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encounterDescriptionLabel.setText("Enter Encounter Details:");

        heartbeatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartbeatFieldActionPerformed(evt);
            }
        });

        temperatureLabel.setText("Temperature:");

        temperatureField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureFieldActionPerformed(evt);
            }
        });

        bloodPressureLabel.setText("Blood Pressure:");

        bloodPressureField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodPressureFieldActionPerformed(evt);
            }
        });

        diagnosisLabel.setText("Diagnosis:");

        diagnosisField.setColumns(20);
        diagnosisField.setRows(5);
        jScrollPane1.setViewportView(diagnosisField);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(recordEncounterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(descriptionLabel)
                    .addComponent(encounterDescriptionLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(saveButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(diagnosisLabel)
                                .addComponent(temperatureLabel)
                                .addComponent(bloodPressureLabel)
                                .addComponent(heartbeatLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(heartbeatField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(temperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)
                                .addComponent(bloodPressureField)))))
                .addContainerGap(547, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordEncounterButton)
                .addGap(18, 18, 18)
                .addComponent(encounterDescriptionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heartbeatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heartbeatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperatureLabel)
                    .addComponent(temperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodPressureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodPressureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diagnosisLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void recordEncounterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordEncounterButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = patientListTable.getSelectedRow();
        if (selectedIndex <0){
            JOptionPane.showMessageDialog(this, "Please select an entry to view", "Error", HEIGHT);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) patientListTable.getModel();
        
        
        patientName = model.getValueAt(selectedIndex, 1).toString();
        
        heartbeatField.setEditable(true);
        temperatureField.setEditable(true);
        bloodPressureField.setEditable(true);
        diagnosisField.setEditable(true);        
        saveButton.setEnabled(true);
    }//GEN-LAST:event_recordEncounterButtonActionPerformed

    private void heartbeatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartbeatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartbeatFieldActionPerformed

    private void temperatureFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureFieldActionPerformed

    private void bloodPressureFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodPressureFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodPressureFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/connector", "root", "root");
            pst = sqlConn.prepareStatement("insert into encounters(PatientName,Heartbeat,Temperature,BloodPressure,Diagnosis) values (?,?,?,?,?)");
            
            pst.setString(1, patientName);
            pst.setString(2, heartbeatField.getText());
            pst.setString(3, temperatureField.getText());
            pst.setString(4, bloodPressureField.getText());
            pst.setString(5, diagnosisField.getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Encounter recorded successfully", "Success", HEIGHT);
            
            resetForm();
        } catch(Exception e) {
                        JOptionPane.showMessageDialog(this, e, "Error", HEIGHT);

//            JOptionPane.showMessageDialog(this, "Please enter all readings", "Error", HEIGHT);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed
    
    void populateTable() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConnector, username, password);
            pst = sqlConn.prepareStatement("select * from patients");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            int columnCount = stData.getColumnCount();
            
            DefaultTableModel recordTable = (DefaultTableModel) patientListTable.getModel();
            recordTable.setRowCount(0);
            
            while(rs.next()) {
                Vector columnData = new Vector();
                
                for(int i = 0; i <= columnCount; i++) {
                    columnData.add(rs.getString("patient_id"));
                    columnData.add(rs.getString("Name"));
                    columnData.add(rs.getString("Age"));
                    columnData.add(rs.getString("Community"));
                    columnData.add(rs.getString("Gender"));
                } 
                recordTable.addRow(columnData);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    void resetForm() {
        heartbeatField.setText("");
        temperatureField.setText("");
        diagnosisField.setText("");
        bloodPressureField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodPressureField;
    private javax.swing.JLabel bloodPressureLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea diagnosisField;
    private javax.swing.JLabel diagnosisLabel;
    private javax.swing.JLabel encounterDescriptionLabel;
    private javax.swing.JTextField heartbeatField;
    private javax.swing.JLabel heartbeatLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientListTable;
    private javax.swing.JButton recordEncounterButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField temperatureField;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
