/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.dataModels.Doctor;
import model.directories.DoctorDirectory;

/**
 *
 * @author ASUS
 */
public class DoctorSearchPanel extends javax.swing.JPanel {
    JPanel bottomPanel;
    DoctorDirectory allDoctors;
    
    private static final String username = "root";
    private static final String password = "root";
    private static final String dataConnector = "jdbc:mysql://localhost:3306/connector";
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form DoctorSearchPanel
     */
    public DoctorSearchPanel(JPanel bottomPanel, DoctorDirectory allDoctors) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.allDoctors = allDoctors;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleitleLabel = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        doctorListTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 153, 153));

        titleitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleitleLabel.setText("Search Doctors");

        searchLabel.setText("Search:");

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        doctorListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Doctor Name", "Hospital Name", "Specialization", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(doctorListTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleitleLabel))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(titleitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(464, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) doctorListTable.getModel();
        TableRowSorter<DefaultTableModel> ts = new TableRowSorter<>(model);
        doctorListTable.setRowSorter(ts);
        ts.setRowFilter(RowFilter.regexFilter(searchField.getText().toLowerCase().trim()));
    }//GEN-LAST:event_searchFieldKeyReleased

    private void populateTable() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConnector, username, password);
            pst = sqlConn.prepareStatement("select * from doctors");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            int columnCount = stData.getColumnCount();
            
            DefaultTableModel recordTable = (DefaultTableModel) doctorListTable.getModel();
            recordTable.setRowCount(0);
            
            while(rs.next()) {
                Vector columnData = new Vector();
                
                for(int i = 0; i <= columnCount; i++) {
                    columnData.add(rs.getString("doctor_id"));
                    columnData.add(rs.getString("DoctorName"));
                    columnData.add(rs.getString("HospitalName"));
                    columnData.add(rs.getString("Specialization"));
                    columnData.add(rs.getString("Gender"));
                } 
                recordTable.addRow(columnData);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable doctorListTable;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel titleitleLabel;
    // End of variables declaration//GEN-END:variables
}
