/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.dataModels.Hospital;
import model.directories.HospitalDirectory;

/**
 *
 * @author ASUS
 */
public class HospitalViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalViewPanel
     */
    private static final String username = "root";
    private static final String password = "root";
    private static final String dataConnector = "jdbc:mysql://localhost:3306/connector";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    JPanel rightPanel;
    HospitalDirectory allHospitals;
    
    public HospitalViewPanel(JPanel rightPanel, HospitalDirectory allHospitals) {
        initComponents();
        this.rightPanel= rightPanel;
        this.allHospitals = allHospitals;
        
        nameField.setEditable(false);
        communityMenu4.setEnabled(false);
        employeesField.setEditable(false);
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        hospitalListTable = new javax.swing.JTable();
        titleLable = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        communityLabel = new javax.swing.JLabel();
        noOfEmployeesLabel = new javax.swing.JLabel();
        updateTitleLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        employeesField = new javax.swing.JTextField();
        communityMenu4 = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        hospitalListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HospitalID", "Hospital Name", "Community", "Number of Employees"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(hospitalListTable);

        titleLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLable.setText("View Hospitals");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Hospital Name:");

        communityLabel.setText("Community:");

        noOfEmployeesLabel.setText("Number of Employees:");

        updateTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateTitleLabel.setText("Enter new Details:");

        communityMenu4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uptown", "Downtown", "York" }));
        communityMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityMenu4ActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateTitleLabel)
                    .addComponent(titleLable)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(noOfEmployeesLabel)
                                .addComponent(communityLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(employeesField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(communityMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(titleLable)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addGap(44, 44, 44)
                .addComponent(updateTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(communityLabel)
                    .addComponent(communityMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfEmployeesLabel)
                    .addComponent(employeesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(saveButton)
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hospitalListTable.getSelectedRow();
        if(selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select an entry to be deleted", "Error", HEIGHT);
        } else {
            DefaultTableModel model = (DefaultTableModel) hospitalListTable.getModel();
            try {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConnector, username, password);
                pst = sqlConn.prepareStatement("DELETE FROM hospitals WHERE hospital_id = ?;");

                pst.setString(1, model.getValueAt(selectedIndex, 0).toString());

                pst.executeUpdate();
                populateTable();

                JOptionPane.showMessageDialog(this, "Hospital Deleted Successfully", "Update", HEIGHT);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void communityMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityMenu4ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hospitalListTable.getSelectedRow();
        if (selectedIndex <0){
            JOptionPane.showMessageDialog(this, "Please select an entry to view", "Error", HEIGHT);
            return;
        }
        
        nameField.setEditable(true);
        communityMenu4.setEnabled(true);
        employeesField.setEditable(true);
        
        DefaultTableModel model = (DefaultTableModel) hospitalListTable.getModel();
        nameField.setText(model.getValueAt(selectedIndex, 1).toString());
        communityMenu4.setSelectedItem(model.getValueAt(selectedIndex, 2).toString());
        employeesField.setText(model.getValueAt(selectedIndex, 3).toString());
    }//GEN-LAST:event_updateButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hospitalListTable.getSelectedRow();
        if(selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select an entry to be updated", "Error", HEIGHT);
        } else {
            try {
                DefaultTableModel model = (DefaultTableModel) hospitalListTable.getModel();
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConnector, username, password);
                pst = sqlConn.prepareStatement("update hospitals set HospitalName = ?, Community = ?, NumberOfEmployees = ? where hospital_id = ?");

                pst.setString(1, nameField.getText());
                pst.setString(2, communityMenu4.getSelectedItem().toString());
                pst.setString(3, employeesField.getText());
                pst.setString(4, model.getValueAt(selectedIndex, 0).toString());

                pst.executeUpdate();
                populateTable();
                emptyTextFields();

                JOptionPane.showMessageDialog(this, "Hospital Updated Successfully", "Update", HEIGHT);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    
    private void emptyTextFields() {
        nameField.setText("");
        communityMenu4.setSelectedIndex(0);
        employeesField.setText("");
        
        nameField.setEditable(false);
        communityMenu4.setEnabled(false);
        employeesField.setEditable(false);
    }
    
    public void populateTable() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConnector, username, password);
            pst = sqlConn.prepareStatement("select * from hospitals");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            int columnCount = stData.getColumnCount();
            
            DefaultTableModel recordTable = (DefaultTableModel) hospitalListTable.getModel();
            recordTable.setRowCount(0);
            
            while(rs.next()) {
                Vector columnData = new Vector();
                
                for(int i = 0; i <= columnCount; i++) {
                    columnData.add(rs.getString("hospital_id"));
                    columnData.add(rs.getString("HospitalName"));
                    columnData.add(rs.getString("Community"));
                    columnData.add(rs.getString("NumberOfEmployees"));
                } 
                recordTable.addRow(columnData);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel communityLabel;
    private javax.swing.JComboBox<String> communityMenu4;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField employeesField;
    private javax.swing.JTable hospitalListTable;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel noOfEmployeesLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLable;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel updateTitleLabel;
    // End of variables declaration//GEN-END:variables
}
