/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ViewDoctorsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDoctorsPanel
     */
    private static final String username = "root";
    private static final String password = "root";
    private static final String dataConnector = "jdbc:mysql://localhost:3306/connector";
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
        
    public ViewDoctorsPanel() {
        initComponents();
        
        populateTable();
        usernameField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane = new javax.swing.JScrollPane();
        doctorListTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        mainTitleLabel1 = new javax.swing.JLabel();
        specializationLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        specializationField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        nameField = new javax.swing.JTextField();
        femaleButton = new javax.swing.JRadioButton();
        hospitalNameLabel = new javax.swing.JLabel();
        otherGenderButton = new javax.swing.JRadioButton();
        hospitalNameField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        doctorListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Username", "Doctor Name", "Hospital Name", "Specialization", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(doctorListTable);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setText("Search Doctors");

        deleteButton.setText("Delete Entry");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        viewButton.setText("View Details");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        mainTitleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainTitleLabel1.setText("Edit Profile:");

        specializationLabel.setText("Specialization:");

        usernameLabel.setText("Username:");

        specializationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specializationFieldActionPerformed(evt);
            }
        });

        usernameField.setBackground(new java.awt.Color(204, 204, 204));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        genderLabel.setText("Gender:");

        nameLabel.setText("Name:");

        genderButtonGroup.add(maleButton);
        maleButton.setText("Male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        genderButtonGroup.add(femaleButton);
        femaleButton.setText("Female");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        hospitalNameLabel.setText("Hospital Name:");

        genderButtonGroup.add(otherGenderButton);
        otherGenderButton.setText("Other");
        otherGenderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherGenderButtonActionPerformed(evt);
            }
        });

        hospitalNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalNameFieldActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(viewButton)
                        .addGap(193, 193, 193)
                        .addComponent(deleteButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nameLabel)
                                    .addGap(21, 21, 21))
                                .addComponent(usernameLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hospitalNameLabel)
                            .addGap(18, 18, 18)
                            .addComponent(hospitalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(specializationLabel)
                    .addComponent(genderLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(specializationField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(maleButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(femaleButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(otherGenderButton)))))
                    .addComponent(mainTitleLabel1))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainTitleLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hospitalNameLabel)
                            .addComponent(hospitalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(maleButton)
                            .addComponent(femaleButton)
                            .addComponent(otherGenderButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(specializationLabel)
                            .addComponent(specializationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewButton)
                            .addComponent(deleteButton))))
                .addContainerGap(454, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = doctorListTable.getSelectedRow();
        if(selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select an entry to be deleted", "Error", HEIGHT);
        } else {
            DefaultTableModel model = (DefaultTableModel) doctorListTable.getModel();
            try {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConnector, username, password);
                pst = sqlConn.prepareStatement("DELETE FROM doctors WHERE doctor_id = ?;");

                pst.setString(1, model.getValueAt(selectedIndex, 0).toString());

                pst.executeUpdate();
                populateTable();

                JOptionPane.showMessageDialog(this, "Doctor Deleted Successfully", "Update", HEIGHT);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = doctorListTable.getSelectedRow();
        if (selectedIndex <0){
            JOptionPane.showMessageDialog(this, "Please select an entry to view", "Error", HEIGHT);
            return;
        }
             
        DefaultTableModel model = (DefaultTableModel) doctorListTable.getModel();
        
        
        usernameField.setText(model.getValueAt(selectedIndex, 1).toString());
        nameField.setText(model.getValueAt(selectedIndex, 2).toString());
        hospitalNameField.setText(model.getValueAt(selectedIndex, 3).toString());

        if(model.getValueAt(selectedIndex, 5).toString().equals("Male"))
            maleButton.setEnabled(true);
        else if(model.getValueAt(selectedIndex, 5).toString().equals("Female"))
            femaleButton.setEnabled(true);
        else
            otherGenderButton.setEnabled(true);
        
        specializationField.setText(model.getValueAt(selectedIndex, 4).toString());
    }//GEN-LAST:event_viewButtonActionPerformed

    private void specializationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specializationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specializationFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void otherGenderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherGenderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherGenderButtonActionPerformed

    private void hospitalNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalNameFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = doctorListTable.getSelectedRow();
        if(selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select an entry to be updated", "Error", HEIGHT);
        } else {
            try{
                DefaultTableModel model = (DefaultTableModel) doctorListTable.getModel();
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConnector, username, password);
                pst = sqlConn.prepareStatement("update doctors set DoctorName = ?, HospitalName = ?, Gender = ?, Specialization = ? where doctor_id = ?");

                pst.setString(1, nameField.getText());
                pst.setString(2, hospitalNameField.getText());
                
                if(maleButton.isSelected()) {
                    pst.setString(3, "Male");
                } else if(femaleButton.isSelected()) {
                    pst.setString(3, "Female");
                } else if(otherGenderButton.isSelected()) {
                    pst.setString(3, "Other");
                } else {
                    JOptionPane.showMessageDialog(this, "Please select a Gender option", "Error", HEIGHT);
                    return;
                }
                pst.setString(4, specializationField.getText());
                pst.setString(5, model.getValueAt(selectedIndex, 0).toString());

                pst.executeUpdate();
                populateTable();
                emptyTextFields();


                JOptionPane.showMessageDialog(this, "The selected entry is successfully updated", "Updated", HEIGHT);

            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Please enter all your details", "Error", HEIGHT);
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void populateTable() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConnector, username, password);
            pst = sqlConn.prepareStatement("select * from doctors");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            int columnCount = stData.getColumnCount();
            
            DefaultTableModel recordTable = (DefaultTableModel) doctorListTable.getModel();
            recordTable.setRowCount(0);
            
            while(rs.next()) {
                Vector columnData = new Vector();
                
                for(int i = 0; i <= columnCount; i++) {
                    columnData.add(rs.getString("doctor_id"));
                    columnData.add(rs.getString("Username"));
                    columnData.add(rs.getString("DoctorName"));
                    columnData.add(rs.getString("HospitalName"));
                    columnData.add(rs.getString("Specialization"));
                    columnData.add(rs.getString("Gender"));
                } 
                recordTable.addRow(columnData);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void emptyTextFields() {
        usernameField.setText("");
        nameField.setText("");
        hospitalNameField.setText("");
        
        if(maleButton.isEnabled())
            maleButton.setEnabled(false);
        else if(femaleButton.isEnabled())
            femaleButton.setEnabled(false);
        else
            otherGenderButton.setEnabled(false);
        
        specializationField.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable doctorListTable;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField hospitalNameField;
    private javax.swing.JLabel hospitalNameLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel mainTitleLabel1;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JRadioButton otherGenderButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField specializationField;
    private javax.swing.JLabel specializationLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
